### ISSUE TITLE
At run give error "undefined method get_method_namespaces()"

### ISSUE THREAD

**Issue by ivanioannovich** [ilteoood/tele_uploader#6]
At run "php.exe bot.php"
gives an error:
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in D:\tm\bot.php on line 43

Fatal error: Uncaught Error: Call to undefined method danog\MadelineProto\MTProto::get_method_namespaces() in D:\tm\vendor\danog\madelineproto\src\danog\MadelineProto\API.php:167
Stack trace:
#0 D:\tm\vendor\danog\madelineproto\src\danog\MadelineProto\API.php(99): danog\MadelineProto\API->APIFactory()
#1 D:\tm\vendor\danog\magicalserializer\src\danog\Serializable.php(35): danog\MadelineProto\API->__magic_construct(Array)
#2 D:\tm\BotManager.php(19): danog\MadelineProto\API->__construct(Array)
#3 D:\tm\bot.php(25): makeLogin()
#4 {main}
  thrown in D:\tm\vendor\danog\madelineproto\src\danog\MadelineProto\API.php on line 167

D:\tm\ - root dir

**Comment by ivanioannovich** [comment]
As far as I understand, the problem is MadelineProto. Solved the problem by excluding it from composer.json. Edited bot.php, I added "include 'madeline.php';". MadelineProto downloaded from github. Works. Thanks for developing.
